# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./QuizApp
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install SonarCloud Scanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet sonarscanner begin /k:"egaychukov_QuizApp" /o:"egaychukov" /d:sonar.login="${SONAR_TOKEN}" /d:sonar.host.url="https://sonarcloud.io"
        dotnet build
        dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
