# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./QuizApp
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x


    - name: List all files
      id: lister
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "."
        type: "*"
    - name: Output results
      run: |
        echo "Found ${{ steps.lister.outputs.path_count }} files:"
        for path in ${{ steps.lister.outputs.paths }}; do
        echo $path
        done
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: powershell
      run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"egaychukov_QuizApp" /o:"egaychukov" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build --verbosity normal
    - name: Display test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
          name: xUnit Tests
          path: QuizApp\QuizAppTests\TestResults\*.trx
          reporter: dotnet-trx
